name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: inventoryapp_dev
          MYSQL_USER: laravel
          MYSQL_PASSWORD: inventory@app_dev
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Install MySQL CLient
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-client
        
    - name: Wait for MySQL to be ready
      run: |
          until mysql -h 127.0.0.1 -u root -p inventory@app_dev -e "SHOW DATABASES;" > /dev/null 2>&1; do
            sleep 1
          done
    - name: Configure Database
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: inventoryapp_dev
        DB_USERNAME: root
        DB_PASSWORD: inventory@app_dev
      run: php artisan migrate --force
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: inventoryapp_dev
        DB_USERNAME: root
        DB_PASSWORD: inventory@app_dev
      run: php artisan test
